name: deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: sam build
        uses: docker://public.ecr.aws/sam/build-python3.12:1
        with:
          entrypoint: /bin/bash
          #args: 'sam build'
          args: 'which sam'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
      - name: sam deploy
        uses: docker://public.ecr.aws/sam/build-python3.12:1
        with:
          entrypoint: /bin/bash
          args: 'sam deploy --config-env dev --resolve-s3 --no-fail-on-empty-changeset --no-confirm-changeset'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
